spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: ${SPRING_JPA_DATABASE-PLATFORM}
twilio:
  account_sid: ACaff272610c2fab8111f663210b7a4c3e
  auth_token: 08d82281d67c6b700df0a82bc32e06ca
  trial_number: +15404538430
