version: '3.1'
services:
  postgres-db:
    container_name: 'postgres-db'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=smsdevdb
      - POSTGRES_USER=smsdevuser
      - POSTGRES_PASSWORD=password
  postgres-junit-db:
    container_name: 'postgres-junit-db'
    image: postgres:alpine
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_DB=smsdevdb
      - POSTGRES_USER=smsdevuser
      - POSTGRES_PASSWORD=password