insert into questions (key_word, question)
values ('ECHO TEST', 'Working SMS service'),
       ('Q1-R', 'Jeg trives best på reise, men for tiden er maten dyr. Livet ruller og går, men av og til blir jeg parkert og står. Hvor bor jeg?'),
       ('Q1-H', 'Bilens hjem.'),
       ('Q2-R', 'Jeg bringer barna sammen, her er det alltid gøy. Selv om det av og til kan bli litt mye støy. Husker dere meg?'),
       ('Q2-H', 'Ja, husker er blandt annet noe jeg har.'),
       ('Q3-R', 'Uten meg er det kaldt og mørkt. Jeg er dette nabolagets forsørger, og har et lite blått hus som skall. Rundt meg er det plass til mange gjester. Hvor står jeg?'),
       ('Q3-H', 'Parkeringsplassens monument.'),
       ('Q4-R', 'Jeg gikk en tur på stien og... Kom og finn meg!'),
       ('Q4-H', 'Hva er mellom skogen og hekken, ved innkjørselen?'),
       ('Q5-R', 'Jeg gjemmer meg på et litt uvanlig sted. Du må være veldig lav for å se meg. Mange mener jeg befinner meg i hagens midtpunkt. Det er som å være fanget på et fort.'),
       ('Q5-H', 'Rammet inn av hvitt rekkverk i hagen.'),
       ('Q6-R', 'Jeg gjemmer meg i det grønne og nyter musikken. Hvor er jeg?'),
       ('Q6-H', 'Det grønne rammer inn Teigens hjem. Hvor er det musikken er hen?'),
       ('Q7-R', 'Jeg er god på kveldene, og har alltid noe å by på. Et show skal du med flammer og musikk få.'),
       ('Q7-H', 'Hører jeg nach? Jeg vet om det perfekte sted.'),
       ('Q8-R', 'Jeg består av 70% vann, men ikke akkurat nå da alkoholen har tatt vannets plass. Håper jeg ikke mister mobilen og ikke må spy i dass.  Fang for neste kode.'),
       ('Q8-H', 'Hosten'),
       ('Q9-R', 'Nå må dere et lite stykke, der hovedveien møter Kvestadåsen. Her ligger jeg og venter. Snart i mål nå!'),
       ('Q9-H', 'Krysset ved hovedveien'),
       ('Q10-R', 'Voff voff! Jeg koser meg ute i gården min. Her kan jeg leke og sove i min lille hule. Jeg har ikke lenger noe å skjule! X marks the spot.'),
       ('Q10-H', 'Rød hundegård');