insert into questions (key_word, question)
values ('ECHO TEST', 'Working SMS service'),
       ('Start Quiz', 'Jeg trives best på reise, men for tiden er maten dyr. Livet ruller og går, men av og til blir jeg parkert og står. Hvor bor jeg?'),
       ('Q1-H', 'Bilens hjem.'),
       ('Garasje', 'Jeg bringer barna sammen, her er det alltid gøy. Selv om det av og til kan bli litt mye støy. Husker dere meg?'),
       ('Q2-H', 'Ja, husker er blandt annet noe jeg har.'),
       ('Lekeplass', 'Uten meg er det kaldt og mørkt. Jeg er dette nabolagets forsørger, og har et lite blått hus som skall. Rundt meg er det plass til mange gjester. Hvor står jeg?'),
       ('Q3-H', 'Parkeringsplassens monument.'),
       ('Strømhus', 'Jeg gikk en tur på stien og... Kom og finn meg!'),
       ('Q4-H', 'Hva er mellom skogen og hekken, ved innkjørselen?'),
       ('Stien', 'Jeg gjemmer meg på et litt uvanlig sted. Du må være veldig lav for å se meg. Mange mener jeg befinner meg i hagens midtpunkt. Det er som å være fanget på et fort.'),
       ('Q5-H', 'Rammet inn av hvitt rekkverk i hagen.'),
       ('Veranda', 'Jeg gjemmer meg i det grønne og nyter musikken. Hvor er jeg?'),
       ('Q6-H', 'Det grønne rammer inn Teigens hjem. Hvor er det musikken er hen?'),
       ('Hekken', 'Jeg er god på kveldene, og har alltid noe å by på. Et show skal du med flammer og musikk få.'),
       ('Q7-H', 'Hører jeg nach? Jeg vet om det perfekte sted.'),
       ('Utestue', 'Jeg består av 70% vann, men ikke akkurat nå da alkoholen har tatt vannets plass. Håper jeg ikke mister mobilen og ikke må spy i dass.  Fang for neste kode.'),
       ('Q8-H', 'Hosten'),
       ('Marte', 'Nå må dere et lite stykke, der hovedveien møter Kvestadåsen. Her ligger jeg og venter. Snart i mål nå!'),
       ('Q9-H', 'Krysset ved hovedveien'),
       ('Krysset', 'Voff voff! Jeg koser meg ute i gården min. Her kan jeg leke og sove i min lille hule. Jeg har ikke lenger noe å skjule! X marks the spot.'),
       ('Q10-H', 'Rød hundegård'),
       ('T1-T', 'Hinderløype-stafett! Alle fra hvert lag skal løpe rundt huset én gang før de gir den til neste. Når alle har vært gjennom skal hele laget rundt sammen. Her er utfordringen at en må være lam fra nakken og ned, en må balansere et egg på en skje, og en er blind og kan ikke bli rørt av andre spillere.'),
       ('T2-H', 'Presisjon er nøkkelen til seier.'),
       ('T2-T', 'Tyrkisk straffekonk! 3 deltakere fra hvert lag skal gjennomføre tyrkisk straffekonk. Her må man først ta en slurk, deretter spinne rundt "kjeglen" 10 ganger før man skyter på mål. Hver deltaker må score 1 mål før de er ferdig.'),
       ('T3-H', 'Her liker vi ikke trafikkregler, vi gjør motsatt'),
       ('T3-T', 'Ho-Ho-Ho! Laget skal velge ut en sekk. Ingen røring! Sekken skal fraktest opp og ned på plenen 3 ganger av 1 på laget. Mellom hver runde skal man ta 3 gode slurker av drinken.'),
       ('T4-H', 'Gag-reflex og stålkontroll?'),
       ('T4-T', 'Spydkast! Hvert lag velger ut en spiller som skal fungere som et timeglass, og en spiller som skal lage spydet. Timeglasset skal chugge en ny drikke, dette definerer en av motstanderene sin tid for øvelsen. Øvelsen går ut på å lage det best mulige spydet. Når tiden din er ute må du stoppe å bygge. Deretter skal lagene konkurrere i å kaste spydet nærmest gitt mål. Spydet må stå i bakken for godkjent kast. 3 forsøk per lag. Eksempel på timeglass: Så lenge en fra lag Hemsedal har drikke i koppen, kan Trysil lage spyd.'),
       ('T5-H', 'Styrke er ikke bare muskler. Tålmodighet tar deg langt.'),
       ('T5-T', 'Påskeegg-spann! Påskeversjonen av den tradisjonelle melkespannøvelsen. Hvert lag velger ut en spiller til å gjennomføre. Spilleren som står lengst, sanker inn øvelsens poeng.'),
       ('T6-H', 'Kropp og sinn fører til vinn'),
       ('T6-T', 'Byggmester Bob! Utform en stol på gitt tid. Laget med den mest funksjonelle stolen vinner. Taperlaget straffes med drikke. Stol er kun godkjent dersom 5/6 i laget har sittet på den.'),